services:
    frontend:
        image: benmadi/offline-task-1-frontend:latest
        ports:
            - "5173:80" # Maps port 5173 on the host to port 80 in the container

    backend:
        image: benmadi/offline-task-1-backend:latest
        ports:
            - "3000:3000" # Maps port 3000 on the host to port 3000 in the container
        env_file:
            - ./Server/.env
        depends_on:
            - db

    db:
        image: benmadi/mysql:8
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: NotesApp
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
